name: 🚧 Danger
on:
  pull_request:
    branches:
      - main
permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: read

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - uses: MeilCli/danger-action@v5
        with:
          plugins_file: ".github/Gemfile"
          install_path: "vendor/bundle"
          danger_file: ".github/Dangerfile"
          danger_id: "danger-pr"
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
